import os
import argparse
from datetime import datetime

import yaml
import numpy as np

import torch
import torch.nn as nn
from torchvision import datasets, transforms

from BitNetMCU import QuantizedModel, BitLinear, BitConv2d, Activation

try:
    import importlib
except Exception:
    importlib = None


def create_run_name(hyperparameters):
    runname = (
        hyperparameters["runtag"]
        + "_"
        + hyperparameters["model"]
        + ("_Aug" if hyperparameters.get("augmentation", False) else "")
        + "_BitMnist_"
        + hyperparameters["QuantType"]
        + "_width"
        + str(hyperparameters["network_width1"])
        + "_"
        + str(hyperparameters["network_width2"])
        + "_"
        + str(hyperparameters["network_width3"])
        + "_epochs"
        + str(hyperparameters["num_epochs"])
    )

    hyperparameters["runname"] = runname
    return runname


def make_bitlinear(in_features, out_features, QuantType, NormType, WScale):
    try:
        return BitLinear(
            in_features,
            out_features,
            QuantType=QuantType,
            NormType=NormType,
            WScale=WScale,
        )
    except TypeError:
        try:
            return BitLinear(
                in_features,
                out_features,
                QuantType,
                NormType,
                WScale,
            )
        except TypeError:
            print("Warning: BitLinear failed. Falling back to nn.Linear.")
            return nn.Linear(in_features, out_features)


def load_model(model_name, params):
    """
    Create the model using the same parameters used during training.
    """

    if importlib is None:
        raise ValueError("Cannot import models.py")

    try:
        module = importlib.import_module("models")
        model_class = getattr(module, model_name)

        kwargs = dict(
            network_width1=params["network_width1"],
            network_width2=params["network_width2"],
            network_width3=params["network_width3"],
            QuantType=params["QuantType"],
            NormType=params["NormType"],
            WScale=params["WScale"],
        )

        if "cnn_width" in params:
            kwargs["cnn_width"] = params["cnn_width"]

        if "num_classes" in params:
            kwargs["num_classes"] = params["num_classes"]

        return model_class(**kwargs)

    except AttributeError:
        raise ValueError(
            f"Model {model_name} not found in models.py or exportquant.py"
        )


def export_to_hfile(
    quantized_model,
    filename,
    runname,
    modelname="",
    input_dim=None,
    num_classes=None,
):
    if not quantized_model.quantized_model:
        raise ValueError("quantized_model is empty or None")

    max_n_activations = max(
        [
            layer["incoming_weights"]
            for layer in quantized_model.quantized_model
            if "incoming_weights" in layer
        ]
    )

    with open(filename, "w") as f:

        f.write("// Automatically generated header file\n")
        f.write(f"// Date: {datetime.now()}\n")
        f.write(f"// Quantized model exported from {runname}.pth\n")
        f.write("// Generated by exportquant.py\n\n")

        f.write("#include <stdint.h>\n\n")

        f.write("#ifndef BITNETMCU_MODEL_H\n")
        f.write("#define BITNETMCU_MODEL_H\n\n")

        f.write("// Model class name\n")
        f.write(f"#define MODEL_{modelname}\n\n")

        if input_dim is not None:
            f.write(f"#define MODEL_INPUT_DIM {input_dim}\n")

        if num_classes is not None:
            f.write(f"#define MODEL_NUM_CLASSES {num_classes}\n\n")

        f.write(
            f"#define NUM_LAYERS {len(quantized_model.quantized_model)}\n"
        )
        f.write(
            f"#define MAX_N_ACTIVATIONS {max_n_activations}\n\n"
        )

        for layer_info in quantized_model.quantized_model:

            layer = f'L{layer_info["layer_order"]}'

            # ============================================================
            # BitLinear
            # ============================================================

            if layer_info["layer_type"] == "BitLinear":

                incoming_weights = layer_info["incoming_weights"]
                outgoing_weights = layer_info["outgoing_weights"]
                bpw = layer_info["bpw"]

                weights = np.array(
                    layer_info["quantized_weights"]
                )

                quantization_type = layer_info[
                    "quantization_type"
                ]

                if (bpw * incoming_weights % 32) != 0:
                    raise ValueError(
                        "Size mismatch: incoming weights must pack "
                        "to 32-bit boundary. "
                        f"Layer={layer}, "
                        f"incoming={incoming_weights}, "
                        f"bpw={bpw}, "
                        f"bits={bpw * incoming_weights}."
                    )

                print(
                    f"Layer: {layer} "
                    f"Quantization type: <{quantization_type}>, "
                    f"Bits per weight: {bpw}, "
                    f"Incoming: {incoming_weights}, "
                    f"Outgoing: {outgoing_weights}"
                )

                data_type = np.uint32

                # --------------------------------------------------------
                # Binary
                # --------------------------------------------------------

                if quantization_type in (
                    "Binary",
                    "BinaryBalanced",
                ):

                    encoded_weights = np.where(
                        weights < 0,
                        0,
                        1,
                    ).astype(data_type)

                    QuantID = 1

                # --------------------------------------------------------
                # 2-bit symmetric
                # --------------------------------------------------------

                elif quantization_type == "2bitsym":

                    encoded_weights = (
                        (weights < 0).astype(data_type) << 1
                    ) | (
                        np.floor(
                            np.abs(weights)
                        ).astype(data_type)
                    )

                    QuantID = 2

                # --------------------------------------------------------
                # 4-bit symmetric
                # --------------------------------------------------------

                elif quantization_type == "4bitsym":

                    encoded_weights = (
                        (weights < 0).astype(data_type) << 3
                    ) | (
                        np.floor(
                            np.abs(weights)
                        ).astype(data_type)
                    )

                    QuantID = 4

                # --------------------------------------------------------
                # 4-bit
                # --------------------------------------------------------

                elif quantization_type == "4bit":

                    encoded_weights = (
                        np.floor(weights).astype(data_type)
                        & 15
                    )

                    QuantID = 8 + 4

                # --------------------------------------------------------
                # 8-bit
                # --------------------------------------------------------

                elif quantization_type == "8bit":

                    encoded_weights = (
                        np.floor(weights).astype(data_type)
                        & 255
                    )

                    QuantID = 8 + 8

                # --------------------------------------------------------
                # NF4
                # --------------------------------------------------------

                elif quantization_type == "NF4":

                    levels = np.array(
                        [
                            -1.0,
                            -0.6962,
                            -0.5251,
                            -0.3949,
                            -0.2844,
                            -0.1848,
                            -0.0911,
                            0.0,
                            0.0796,
                            0.1609,
                            0.2461,
                            0.3379,
                            0.4407,
                            0.5626,
                            0.723,
                            1.0,
                        ]
                    )

                    encoded_weights = np.argmin(
                        np.abs(
                            weights[:, :, np.newaxis]
                            - levels
                        ),
                        axis=2,
                    )

                    QuantID = 32 + 4

                # --------------------------------------------------------
                # FP130
                # --------------------------------------------------------

                elif quantization_type == "FP130":

                    encoded_weights = (
                        (weights < 0).astype(data_type) << 3
                    ) | (
                        np.floor(
                            np.log2(
                                np.abs(weights)
                            )
                        ).astype(data_type)
                    )

                    QuantID = 16 + 4

                # --------------------------------------------------------
                # Ternary
                # --------------------------------------------------------

                elif quantization_type == "Ternary":

                    n_outputs, n_inputs = weights.shape

                    if n_inputs % 10 != 0:

                        pad_size = 10 - (
                            n_inputs % 10
                        )

                        print(
                            f"WARNING: Ternary layer {layer} "
                            f"has {n_inputs} inputs, "
                            f"padding with {pad_size} zeros."
                        )

                        weights = np.pad(
                            weights,
                            (
                                (0, 0),
                                (0, pad_size),
                            ),
                            mode="constant",
                            constant_values=0,
                        )

                        n_inputs = weights.shape[1]

                    trit_values = np.where(
                        weights == 1,
                        0,
                        np.where(
                            weights == -1,
                            1,
                            2,
                        ),
                    ).astype(np.uint32)

                    packed_row_size = n_inputs // 10

                    packed_weights = np.zeros(
                        (
                            n_outputs,
                            packed_row_size,
                        ),
                        dtype=np.uint16,
                    )

                    for row in range(n_outputs):

                        for word_idx in range(
                            packed_row_size
                        ):

                            start = word_idx * 10

                            chunk = trit_values[
                                row,
                                start:start + 10,
                            ]

                            value = 0

                            for t in range(10):
                                value = (
                                    value * 3
                                    + chunk[t]
                                )

                            packed = (
                                value * 65536
                                + 59048
                            ) // 59049

                            packed_weights[
                                row,
                                word_idx
                            ] = packed

                    QuantID = 64

                    f.write(
                        f"// Layer: {layer}\n"
                    )

                    f.write(
                        f"// QuantType: "
                        f"{quantization_type}\n"
                    )

                    f.write(
                        f"#define {layer}_active\n"
                    )

                    f.write(
                        f"#define {layer}_bitperweight "
                        f"{QuantID}\n"
                    )

                    f.write(
                        f"#define {layer}_incoming_weights "
                        f"{n_inputs}\n"
                    )

                    f.write(
                        f"#define {layer}_outgoing_weights "
                        f"{outgoing_weights}\n"
                    )

                    f.write(
                        f"const uint16_t "
                        f"{layer}_weights[] = {{"
                    )

                    for i, data in enumerate(
                        packed_weights.flatten()
                    ):

                        if i % 10 == 0:
                            f.write("\n\t")

                        f.write(
                            f"0x{data:04x},"
                        )

                    f.write("\n};\n\n")

                    continue

                else:

                    print(
                        f"Skipping layer {layer}. "
                        f"Unsupported quantization type: "
                        f"{quantization_type}"
                    )

                    continue

                # --------------------------------------------------------
                # Pack weights into 32-bit words
                # --------------------------------------------------------

                weight_per_word = 32 // bpw

                reshaped_array = encoded_weights.reshape(
                    -1,
                    weight_per_word,
                )

                bit_positions = (
                    32
                    - bpw
                    - np.arange(
                        weight_per_word,
                        dtype=data_type,
                    ) * bpw
                )

                packed_weights = np.bitwise_or.reduce(
                    reshaped_array << bit_positions,
                    axis=1,
                ).view(data_type)

                f.write(
                    f"// Layer: {layer}\n"
                )

                f.write(
                    f"// QuantType: "
                    f"{quantization_type}\n"
                )

                f.write(
                    f"#define {layer}_active\n"
                )

                f.write(
                    f"#define {layer}_bitperweight "
                    f"{QuantID}\n"
                )

                f.write(
                    f"#define {layer}_incoming_weights "
                    f"{incoming_weights}\n"
                )

                f.write(
                    f"#define {layer}_outgoing_weights "
                    f"{outgoing_weights}\n"
                )

                f.write(
                    f"const uint32_t "
                    f"{layer}_weights[] = {{"
                )

                for i, data in enumerate(
                    packed_weights.flatten()
                ):

                    if i & 7 == 0:
                        f.write("\n\t")

                    f.write(
                        f"0x{data:08x},"
                    )

                f.write(
                    "\n}; "
                    "// first channel is topmost bit\n\n"
                )

            # ============================================================
            # BitConv2d
            # ============================================================

            elif layer_info["layer_type"] == "BitConv2d":

                in_channels = layer_info[
                    "in_channels"
                ]

                out_channels = layer_info[
                    "out_channels"
                ]

                groups = layer_info["groups"]

                kernel_size = layer_info[
                    "kernel_size"
                ][0]

                bpw = layer_info["bpw"]

                weights = np.array(
                    layer_info[
                        "quantized_weights"
                    ]
                )

                # --------------------------------------------------------
                # Spatial dimensions
                #
                # Current CNN architecture:
                #
                # Input: 32x32
                #
                # L2 Conv3x3 -> 30x30
                # L4 Conv3x3 -> 28x28
                # L6 MaxPool2x2 -> 14x14
                # L7 Conv3x3 -> 12x12
                # L9 MaxPool2x2 -> 6x6
                # --------------------------------------------------------

                layer_order = layer_info[
                    "layer_order"
                ]

                if layer_order == 2:

                    incoming_x = 32
                    incoming_y = 32

                    outgoing_x = 30
                    outgoing_y = 30

                elif layer_order == 4:

                    incoming_x = 30
                    incoming_y = 30

                    outgoing_x = 28
                    outgoing_y = 28

                elif layer_order == 7:

                    incoming_x = 14
                    incoming_y = 14

                    outgoing_x = 12
                    outgoing_y = 12

                else:

                    raise ValueError(
                        "Unexpected BitConv2d layer order "
                        f"{layer_order}. "
                        "Expected 2, 4, or 7 for "
                        "the current CNNMNIST 32x32 model."
                    )

                f.write(
                    f"// Layer: {layer} "
                    f"Convolutional\n"
                )

                f.write(
                    f"#define {layer}_active\n"
                )

                f.write(
                    f"#define {layer}_type BitConv2d\n"
                )

                f.write(
                    f"#define {layer}_in_channels "
                    f"{in_channels}\n"
                )

                f.write(
                    f"#define {layer}_out_channels "
                    f"{out_channels}\n"
                )

                f.write(
                    f"#define {layer}_incoming_x "
                    f"{incoming_x}\n"
                )

                f.write(
                    f"#define {layer}_incoming_y "
                    f"{incoming_y}\n"
                )

                f.write(
                    f"#define {layer}_outgoing_x "
                    f"{outgoing_x}\n"
                )

                f.write(
                    f"#define {layer}_outgoing_y "
                    f"{outgoing_y}\n"
                )

                f.write(
                    f"#define {layer}_kernel_size "
                    f"{kernel_size}\n"
                )

                f.write(
                    f"#define {layer}_stride 1\n"
                )

                f.write(
                    f"#define {layer}_padding 0\n"
                )

                f.write(
                    f"#define {layer}_groups "
                    f"{groups}\n"
                )

                f.write(
                    f"#define {layer}_bitperweight "
                    f"{bpw}\n"
                )

                f.write(
                    f"const int8_t "
                    f"{layer}_weights[] = {{"
                )

                for i, data in enumerate(
                    weights.flatten()
                ):

                    if i % 16 == 0:
                        f.write("\n\t")

                    f.write(
                        f"{int(data)},"
                    )

                f.write("\n};\n\n")

            # ============================================================
            # MaxPool2d
            # ============================================================

            elif layer_info["layer_type"] == "MaxPool2d":

                pool_size = layer_info[
                    "kernel_size"
                ]

                layer_order = layer_info[
                    "layer_order"
                ]

                # --------------------------------------------------------
                # Current CNN:
                #
                # L6: 28x28 -> 14x14
                # L9: 12x12 -> 6x6
                # --------------------------------------------------------

                if layer_order == 6:

                    incoming_x = 28
                    incoming_y = 28

                    outgoing_x = 14
                    outgoing_y = 14

                elif layer_order == 9:

                    incoming_x = 12
                    incoming_y = 12

                    outgoing_x = 6
                    outgoing_y = 6

                else:

                    raise ValueError(
                        "Unexpected MaxPool2d layer order "
                        f"{layer_order}. "
                        "Expected 6 or 9 for "
                        "the current CNNMNIST 32x32 model."
                    )

                f.write(
                    f"#define {layer}_active\n"
                )

                f.write(
                    f"#define {layer}_type MaxPool2d\n"
                )

                f.write(
                    f"#define {layer}_pool_size "
                    f"{pool_size}\n"
                )

                f.write(
                    f"#define {layer}_incoming_x "
                    f"{incoming_x}\n"
                )

                f.write(
                    f"#define {layer}_incoming_y "
                    f"{incoming_y}\n"
                )

                f.write(
                    f"#define {layer}_outgoing_x "
                    f"{outgoing_x}\n"
                )

                f.write(
                    f"#define {layer}_outgoing_y "
                    f"{outgoing_y}\n\n"
                )

        f.write("#endif\n")


# ================================================================
# Main
# ================================================================

if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description="Export quantized BitNetMCU model"
    )

    parser.add_argument(
        "--params",
        type=str,
        help="Name of parameter YAML file",
        default="trainingparameters.yaml",
    )

    args = parser.parse_args()

    paramname = args.params

    print(
        f"Load parameters from file: {paramname}"
    )

    with open(paramname) as f:
        hyperparameters = yaml.safe_load(f)

    hyperparameters.setdefault(
        "augmentation",
        False,
    )

    hyperparameters.setdefault(
        "network_width3",
        0,
    )

    hyperparameters.setdefault(
        "dropout",
        0.0,
    )

    runname = create_run_name(
        hyperparameters
    )

    print(
        "Run name:",
        runname
    )

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    print(
        "Device:",
        device
    )

    # ================================================================
    # FACE dataset
    # ================================================================

    dataset_name = hyperparameters.get(
        "dataset",
        "FACE",
    ).upper()

    if dataset_name != "FACE":

        raise ValueError(
            "This exportquant.py is prepared "
            "for dataset: FACE only."
        )

    data_root = hyperparameters[
        "data_root"
    ]

    test_dir = os.path.join(
        data_root,
        hyperparameters["test_folder"],
    )

    transform = transforms.Compose(
        [
            transforms.Grayscale(
                num_output_channels=1
            ),

            transforms.Resize(
                (32, 32)
            ),

            transforms.ToTensor(),

            transforms.Normalize(
                (0.5,),
                (0.5,),
            ),
        ]
    )

    test_data = datasets.ImageFolder(
        test_dir,
        transform=transform,
    )

    num_classes = len(
        test_data.classes
    )

    input_dim = 32 * 32

    print(
        "Test samples:",
        len(test_data)
    )

    print(
        "Test classes:",
        test_data.classes
    )

    print(
        "Input size:",
        input_dim
    )

    hyperparameters[
        "num_classes"
    ] = num_classes

    hyperparameters[
        "input_dim"
    ] = input_dim

    # ================================================================
    # Create model
    # ================================================================

    model = load_model(
        hyperparameters["model"],
        hyperparameters,
    ).to(device)

    if hyperparameters["model"] == "CNNMNIST":

        dummy_input = torch.randn(
            1,
            1,
            32,
            32,
        ).to(device)

    else:

        dummy_input = torch.randn(
            1,
            input_dim,
        ).to(device)

    with torch.no_grad():

        dummy_output = model(
            dummy_input
        )

    print(
        "Model output shape:",
        dummy_output.shape
    )

    print(
        "Expected classes:",
        num_classes
    )

    if dummy_output.shape[1] != num_classes:

        raise ValueError(
            f"Model output mismatch. "
            f"Model outputs "
            f"{dummy_output.shape[1]} classes, "
            f"but dataset needs "
            f"{num_classes} classes."
        )

    # ================================================================
    # Load best checkpoint
    # ================================================================

    model_path = (
        f"modeldata/{runname}.pth"
    )

    best_model_path = (
        f"modeldata/{runname}_best.pth"
    )

    if os.path.exists(
        best_model_path
    ):

        model_path = best_model_path

    if not os.path.exists(
        model_path
    ):

        raise FileNotFoundError(
            f"Cannot find model checkpoint:\n"
            f"{model_path}\n"
            f"Expected either:\n"
            f"modeldata/{runname}.pth\n"
            f"or\n"
            f"modeldata/{runname}_best.pth"
        )

    model.load_state_dict(
        torch.load(
            model_path,
            map_location=torch.device(
                "cpu"
            ),
        )
    )

    print(
        "Loaded checkpoint:",
        model_path
    )

    model = model.to(device)

    model.eval()

    # ================================================================
    # Quantize
    # ================================================================

    print(
        "Quantizing model..."
    )

    quantized_model = QuantizedModel(
        model
    )

    print(
        f"Total number of bits: "
        f"{quantized_model.totalbits()}"
    )

    print(
        f"Total size: "
        f"{quantized_model.totalbits() / 8 / 1024:.4f} KB"
    )

    # ================================================================
    # Export
    # ================================================================

    export_header = hyperparameters.get(
        "export_header",
        "BitNetMCU_model.h",
    )

    print(
        "Exporting model to header file:",
        export_header
    )

    export_to_hfile(
        quantized_model,
        export_header,
        runname,
        hyperparameters["model"],
        input_dim=(
            1024
            if hyperparameters["model"]
            == "CNNMNIST"
            else input_dim
        ),
        num_classes=num_classes,
    )

    print(
        "Export done:",
        export_header
    )
