# Description: Training parameters for BitNetMCU signal classifier

model: 'FCSignal'
dataset: 'SIGNAL'

signal_classes:
  - idle
  - left
  - right

signal_train_dir: 'signal_dataset/split/train'
signal_test_dir: 'signal_dataset/split/test'

samples_per_window: 64
signal_channels: 3
signal_normalize_scale: 16384.0

# Quantization settings
QuantType: '4bitsym'
NormType: 'None'
WScale: 'PerTensor'

# Clipping parameters
maxw_algo: 'octav'
maxw_update_until_epoch: 40
maxw_quantscale: 0.25

# Learning parameters
num_epochs: 40
batch_size: 32
scheduler: 'StepLR'
learning_rate: 0.001

lr_decay: 0.5
step_size: 20
halve_lr_epoch: -1

# Only used if scheduler is CosineWarmRestarts
T_0: 5
T_mult: 4

# Data augmentation
augmentation: false
rotation1: 0
rotation2: 0
elastictransformprobability: 0.0

# Pruning disabled for first signal test
lambda_l1: 0.0
prune_epoch: 9999
prune_groupstoprune: 0
prune_totalgroups: 0

# Model parameters
cnn_width: 0
network_width1: 16
network_width2: 0
network_width3: 0

# Name
runtag: 'Signal4bit'
