dataset: FACE
model: CNNMNIST

data_root: /content/train_validation_test-32_32

train_folder: train
val_folder: validation
test_folder: test

num_classes: 10

num_epochs: 100
batch_size: 32
learning_rate: 0.001
scheduler: Cosine

QuantType: BinaryBalanced
NormType: RMS
WScale: PerTensor

cnn_width: 64
network_width1: 64
network_width2: 32
network_width3: 0

augmentation: false
lambda_l1: 0.0
prune_epoch: -1

maxw_update_until_epoch: 80
maxw_algo: octav
maxw_quantscale: 0.25

runtag: face32
export_header: BitNetMCU_face32_model.h
